# Generated by Django 3.2.9 on 2021-11-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_authority', to=settings.AUTH_USER_MODEL),
        ),
    ]
